export enum ActionsUser {
    USER_LOGIN = "USER_LOGIN",
    USER_ID = "USER_ID",
    USER_PROFILE = "USER_PROFILE",
    USER_RESUME = "USER_RESUME"
}

export enum ActionsService {
    SHOW_POPUP = "SHOW_POPUP",
    CONTROL_METHODS = "CONTROL_METHODS",
    CONTROL_OBJECTS = "CONTROL_OBJECTS",
    USER_QUALIFICATION = "USER_QUALIFICATION",
    USERS_ONLINE_COUNT = "USERS_ONLINE_COUNT",
    SHOW_LICENSE_REQUIRED = 'SHOW_LICENSE_REQUIRED',
}

export enum ActionsBill {
    UPDATE_BILL = "UPDATE_BILL",
    UPDATE_CONTRACT = "UPDATE_CONTRACT",
    UPDATE_PRICE = "UPDATE_PRICE"
}
